[package]
name = "static_stash"
version = "0.2.0"
edition = "2021"

[workspace]
members = [
  "static_stash_macros"
]

[dependencies]
static_stash_macros = { path = "static_stash_macros", version = "0.2.0" }
